FROM ubuntu
MAINTAINER Torrie Fischer <torrie@jbcoin.com>

RUN apt-get update -qq &&\
    apt-get install -qq software-properties-common &&\
    apt-add-repository -y ppa:ubuntu-toolchain-r/test &&\
    apt-add-repository -y ppa:afrank/boost &&\
    apt-get update -qq

RUN apt-get purge -qq libboost1.48-dev &&\
    apt-get install -qq libprotobuf8 libboost1.57-all-dev

RUN mkdir -p /srv/jbcoind/data

VOLUME /srv/jbcoind/data/

ENTRYPOINT ["/srv/jbcoind/bin/jbcoind"]
CMD ["--conf", "/srv/jbcoind/data/jbcoind.cfg"]
EXPOSE 51235/udp
EXPOSE 5005/tcp

ADD ./jbcoind.cfg /srv/jbcoind/data/jbcoind.cfg
ADD ./jbcoind /srv/jbcoind/bin/
